### PR TITLE
1Password Connect Log Inspector Tool

### LINKED ISSUE #12667: Create GitHub repo for our 1password connect server
Repo to be named `dts-onepassword-connect`, and please include the log inspector tooling.

### PR DESCRIPTION
**Pull request by frankhereford**
## Background

I've created the repo to store our configuration and related tooling for the 1Password Connect service we're running.

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/12667. 

## Testing

* Create a virtual environment for this script: `python3 -m venv venv` in the `tooling/log_inspector` directory.
* Create the `.env` file following the template. You can borrow credentials out of your airflow `.env` file.
* Install requirements `pip install -r requirements.txt`
* Execute the script `python check_api_logs.py`

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
Nice! thanks @frankhereford!!!

One small suggestion: to copy your testing instructions in this PR into a README in this directory 😇

**Review by mddilley — COMMENTED** [review]
Code looks good! Just did a quick and I'm getting 404 when I run the script. Is this hitting the right endpoint?
`Failed to fetch data from https://1password.austinmobility.io?limit=50&offset=0, status code: 404`

**Comment by Charlie-Henry** [comment]
Just wanted to +1 what Mike said, I'm trying with my personal 1pass token

**Comment by frankhereford** [comment]
@Charlie-Henry @mddilley Thank you both! I had this URL in my `.env` file `https://1password.austinmobility.io/v1/activity` and I had put in my instructions to put `https://1password.austinmobility.io` in the .env file. 

I've amended the script to need the URL as you have it now in your `.env`s, so you should be able to `git pull` and rerun the test.

I'm also going to add the testing instructions to a `README`; great idea! Thanks y'all!

**Review by Charlie-Henry — APPROVED** [review]
Worked, thanks @frankhereford! Also, do you think it would be useful to print out that list of unique addresses, `ip_set`?

**Review by mddilley — APPROVED** [review]
Works so great when I ran it locally! This code is so useful. 🙏 🚀 🚢

**Pull request merged**
